version: '3'

services:
  database:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: commande
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mscommande
    volumes:
      - /var/lib/postgresql/data
